	# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'JACrowdPurchasingApp' do
	pod 'Facebook-iOS-SDK'
	pod 'ParseUI'
	pod 'Shimmer'
	pod 'Venmo-iOS-SDK', '~>1.3'
	pod 'SSKeychain'
	pod 'JNWSpringAnimation'
	pod 'ParseFacebookUtils'
end

target 'JACrowdPurchasingAppTests' do

end

