	# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'JACrowdPurchasingApp' do
	pod 'Facebook-iOS-SDK'
	pod 'ParseUI'
	pod 'Shimmer'
end

target 'JACrowdPurchasingAppTests' do

end

